Refactor the training during close API of pytorch
the training fails withe error on macos with 128GB memory
RuntimeError: MPS backend out of memory (MPS allocated: 178.54 GiB, other allocations: 3.84 GiB, max allowed: 182.78 GiB).
Tried to allocate 506.25 MiB on private pool.
Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

Signed-off-by: Keshava Munegowda <keshava.gowda@gmail.com>